#!/usr/bin/python
from daemon import runner

from websocketserver import WebSocketServer

class Doorbell():

    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/tty'
        self.stderr_path = '/dev/tty'
        self.pidfile_path =  runner.make_pidlockfile('/var/run/doorbell.pid', 1).path
        self.pidfile_timeout = 5
        self.websocket_server = WebSocketServer()

    def run(self):
        self.websocket_server.start()

doorbell = Doorbell()
daemon_runner = runner.DaemonRunner(doorbell)
daemon_runner.daemon_context.files_preserve=[
    doorbell.websocket_server.gpio_listener.port]
daemon_runner.do_action()
