#!/usr/bin/python

"""
Doorbel daemon
"""

from daemon import runner

from gpiolistener import GPIOListener
from websocketserver import WebSocketServer
from plugins.bell import BellPlugin

class Doorbell():

    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/tty'
        self.stderr_path = '/dev/tty'
        self.pidfile_path = runner.make_pidlockfile(
            '/var/run/doorbell.pid', 1).path
        self.pidfile_timeout = 5
        self.gpio_listener = GPIOListener()
        #self.websocket_server = WebSocketServer(
            #command=getattr(self.gpio_listener, 'listen'))
        self.bell = BellPlugin(
            command=getattr(self.gpio_listener, 'listen'))
        
    def run(self):
        #self.websocket_server.start()
        self.bell.start()
	pass

doorbell = Doorbell()
daemon_runner = runner.DaemonRunner(doorbell)
#if doorbell.gpio_listener.input_device:
daemon_runner.daemon_context.files_preserve=[
    doorbell.gpio_listener.input_device]
daemon_runner.do_action()
